### ISSUE TITLE
Add toilets

### ISSUE THREAD

**Issue by crumblingstatue** [TeamLe-Shop/le-shop#10]
`<Seabasschan> Otherwise can't poop while shopping.`

**Comment by crumblingstatue** [comment]
Ech

**Comment by Sebbyastian** [comment]
YOU CAN'T SERVE FOOD AND TOILET PAPER WITHOUT SERVING A TOILER TO SERVE YOUR CLIENT/S! THIS IS A DISGRACE! BOYCOTT LE-SHOP!
